// <auto-generated />
using System;
using Escuela.DAL.Efc6;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Escuela.DAL.Efc6.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220612191505_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Escuela.Core.Alumno", b =>
                {
                    b.Property<uint>("Dni")
                        .HasColumnType("int unsigned")
                        .HasColumnName("dni");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("apellido");

                    b.Property<byte?>("CursoIdCurso")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("Dni");

                    b.HasIndex("CursoIdCurso");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("Escuela.Core.Curso", b =>
                {
                    b.Property<byte>("IdCurso")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("idCurso");

                    b.Property<byte>("Anio")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Division")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("IdCurso")
                        .HasName("PK_Curso");

                    b.HasIndex("Anio", "Division")
                        .IsUnique()
                        .HasDatabaseName("UQ_Curso_anio_division");

                    b.ToTable("Curso", (string)null);
                });

            modelBuilder.Entity("Escuela.Core.Alumno", b =>
                {
                    b.HasOne("Escuela.Core.Curso", "Curso")
                        .WithMany("Alumnos")
                        .HasForeignKey("CursoIdCurso");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Escuela.Core.Curso", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
